[I 18:20:33.702 NotebookApp] [nb_conda_kernels] enabled, 1 kernels found
[W 2021-12-16 18:20:35.931 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2021-12-16 18:20:35.934 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-16 18:20:35.934 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-16 18:20:35.934 LabApp] 'password_required' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-16 18:20:35.934 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-16 18:20:35.934 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-16 18:20:35.934 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-16 18:20:35.935 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2021-12-16 18:20:35.943 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
[I 2021-12-16 18:20:35.944 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 18:20:36.049 NotebookApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 18:20:36.054 NotebookApp] [nb_conda] enabled
/opt/conda/lib/python3.7/site-packages/jupyter_server_mathjax/app.py:40: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  help=_("""The MathJax.js configuration file that is to be used."""),
[I 18:20:36.121 NotebookApp] Serving notebooks from local directory: /mnt/disks/disk-1/DL-Sys-Perf-Project
[I 18:20:36.121 NotebookApp] Jupyter Notebook 6.4.6 is running at:
[I 18:20:36.121 NotebookApp] http://instance-1:8888/
[I 18:20:36.121 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 18:21:04.758 NotebookApp] 302 GET /tree? (122.173.185.181) 0.870000ms
[I 18:21:10.806 NotebookApp] 302 POST /login?next=%2Ftree%3F (122.173.185.181) 37.770000ms
[I 18:21:30.236 NotebookApp] Kernel started: 6c43392e-62b1-463f-958f-84a3644db916, name: python3
[I 18:48:28.545 NotebookApp] Starting buffering for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 18:48:29.123 NotebookApp] Kernel restarted: 6c43392e-62b1-463f-958f-84a3644db916
[I 18:48:29.615 NotebookApp] Restoring connection for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 18:48:29.808 NotebookApp] Replaying 3 buffered messages
[I 18:49:49.359 NotebookApp] Saving file at /UI_v2.0.ipynb
[I 18:49:49.360 NotebookApp] Saving UI_v2.0.ipynb
[I 19:17:47.381 NotebookApp] Starting buffering for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 19:17:50.590 NotebookApp] Saving file at /UI_v2.0.ipynb
[I 19:17:50.591 NotebookApp] Saving UI_v2.0.ipynb
[I 19:17:52.122 NotebookApp] Kernel restarted: 6c43392e-62b1-463f-958f-84a3644db916
[I 19:17:52.628 NotebookApp] Restoring connection for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 19:17:53.135 NotebookApp] Replaying 3 buffered messages
[I 19:19:49.516 NotebookApp] Saving file at /UI_v2.0.ipynb
[I 19:19:49.517 NotebookApp] Saving UI_v2.0.ipynb
[I 19:21:48.059 NotebookApp] Starting buffering for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 19:21:52.443 NotebookApp] Kernel restarted: 6c43392e-62b1-463f-958f-84a3644db916
[I 19:21:52.984 NotebookApp] Restoring connection for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 19:21:53.490 NotebookApp] Replaying 3 buffered messages
[I 19:22:11.242 NotebookApp] Starting buffering for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 19:22:11.452 NotebookApp] Kernel restarted: 6c43392e-62b1-463f-958f-84a3644db916
[I 19:22:12.015 NotebookApp] Restoring connection for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 19:22:12.204 NotebookApp] Replaying 3 buffered messages
[I 19:23:49.634 NotebookApp] Saving file at /UI_v2.0.ipynb
[I 19:23:49.635 NotebookApp] Saving UI_v2.0.ipynb
[I 20:21:09.342 NotebookApp] Interrupted...
[I 20:21:09.343 NotebookApp] Shutting down 1 kernel
[I 20:21:09.344 NotebookApp] Kernel shutdown: 6c43392e-62b1-463f-958f-84a3644db916
[I 20:21:10.034 NotebookApp] Starting buffering for 6c43392e-62b1-463f-958f-84a3644db916:aa6747d2b6b240e2ae25eb85d7c27106
[I 20:21:10.284 NotebookApp] Kernel shutdown: 6c43392e-62b1-463f-958f-84a3644db916
jupyter_http_over_ws extension initialized. Listening on /http_over_websocket
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 2388, in start
    self.cleanup_kernels()
  File "/opt/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 2167, in cleanup_kernels
    run_sync(self.kernel_manager.shutdown_all())
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 262, in _async_shutdown_all
    futs = [ensure_async(self.shutdown_kernel(kid, now=now)) for kid in set(kids)]
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 262, in <listcomp>
    futs = [ensure_async(self.shutdown_kernel(kid, now=now)) for kid in set(kids)]
  File "/opt/conda/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 304, in shutdown_kernel
    self.pinned_superclass.shutdown_kernel(self, kernel_id, now=now, restart=restart)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 225, in _async_shutdown_kernel
    await ensure_async(km.shutdown_kernel(now, restart))
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 472, in _async_shutdown_kernel
    await ensure_async(self.finish_shutdown(restart=restart))
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/opt/conda/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 162, in delete
    yield maybe_future(sm.delete_session(session_id))
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 250, in wrapper
    runner = Runner(ctx_run, result, future, yielded)
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 741, in __init__
    self.ctx_run(self.run)
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 284, in delete_session
    yield maybe_future(self.kernel_manager.shutdown_kernel(session['kernel']['id']))
  File "/opt/conda/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 304, in shutdown_kernel
    self.pinned_superclass.shutdown_kernel(self, kernel_id, now=now, restart=restart)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 225, in _async_shutdown_kernel
    await ensure_async(km.shutdown_kernel(now, restart))
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 472, in _async_shutdown_kernel
    await ensure_async(self.finish_shutdown(restart=restart))
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "/opt/conda/lib/python3.7/site-packages/nest_asyncio.py", line 87, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[I 21:00:22.582 NotebookApp] [nb_conda_kernels] enabled, 1 kernels found
[W 2021-12-17 21:00:24.705 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2021-12-17 21:00:24.708 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-17 21:00:24.708 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-17 21:00:24.708 LabApp] 'password_required' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-17 21:00:24.708 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-17 21:00:24.708 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-17 21:00:24.708 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-17 21:00:24.709 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2021-12-17 21:00:24.716 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
[I 2021-12-17 21:00:24.716 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 21:00:24.812 NotebookApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 21:00:24.816 NotebookApp] [nb_conda] enabled
/opt/conda/lib/python3.7/site-packages/jupyter_server_mathjax/app.py:40: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  help=_("""The MathJax.js configuration file that is to be used."""),
[I 21:00:24.874 NotebookApp] Serving notebooks from local directory: /mnt/disks/disk-1/DL-Sys-Perf-Project
[I 21:00:24.874 NotebookApp] Jupyter Notebook 6.4.6 is running at:
[I 21:00:24.874 NotebookApp] http://instance-1:8888/
[I 21:00:24.874 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 21:00:30.882 NotebookApp] 302 GET / (122.173.185.181) 0.890000ms
[I 21:03:57.373 NotebookApp] Kernel started: 35e227b4-86bb-4f72-b1ca-00875e3b3201, name: python3
[W 21:05:36.401 NotebookApp] Notebook AllRunsv2.0.ipynb is not trusted
[I 21:05:37.940 NotebookApp] Kernel started: 5bea8b3b-9def-44be-8df8-e9dac4700c75, name: python3
[I 21:07:48.766 NotebookApp] Starting buffering for 35e227b4-86bb-4f72-b1ca-00875e3b3201:8a1fce339dfa42ca97a8520906d98a81
[I 21:07:48.980 NotebookApp] Kernel restarted: 35e227b4-86bb-4f72-b1ca-00875e3b3201
[I 21:07:49.468 NotebookApp] Restoring connection for 35e227b4-86bb-4f72-b1ca-00875e3b3201:8a1fce339dfa42ca97a8520906d98a81
[I 21:07:49.974 NotebookApp] Replaying 3 buffered messages
[I 21:07:52.456 NotebookApp] Starting buffering for 35e227b4-86bb-4f72-b1ca-00875e3b3201:8a1fce339dfa42ca97a8520906d98a81
[I 21:07:52.670 NotebookApp] Kernel restarted: 35e227b4-86bb-4f72-b1ca-00875e3b3201
[I 21:07:53.156 NotebookApp] Restoring connection for 35e227b4-86bb-4f72-b1ca-00875e3b3201:8a1fce339dfa42ca97a8520906d98a81
[I 21:07:53.340 NotebookApp] Replaying 3 buffered messages
[I 21:07:58.101 NotebookApp] Saving file at /UI_v2.0.ipynb
[I 21:07:58.102 NotebookApp] Saving UI_v2.0.ipynb
